name: Hotel-Emirates

on:
  pull:
     branches:
	- main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hotel-Emirates
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hello and welcome!
            Thank you for your *first contribution* to this project.
            We appreciate your effort and look forward to reviewing it soon! 🎉
